# Generated by Django 4.1.3 on 2022-11-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.TextField(max_length=100)),
                ("email", models.EmailField(max_length=30)),
                ("mobile_no", phone_field.models.PhoneField(blank=True, max_length=31)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F"), ("N", "N")],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("availability", models.CharField(max_length=60)),
                ("jobs", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=30)),
                ("date_of_start", models.DateField(blank=True)),
                ("description", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=100)),
                ("from_start", models.DateField()),
                ("to_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.TextField(max_length=100)),
                ("email", models.EmailField(max_length=30)),
                ("mobile_no", phone_field.models.PhoneField(blank=True, max_length=31)),
                ("designation", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "company",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="naukriapp.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=100)),
                ("max_salary", models.FloatField()),
                ("min_salary", models.FloatField()),
                ("employment_type", models.CharField(max_length=30)),
                ("max_experience", models.IntegerField(default=None)),
                ("min_experience", models.IntegerField(default=None)),
                ("location", models.CharField(max_length=50)),
                ("industry_type", models.CharField(max_length=30)),
                (
                    "Posted_by",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="naukriapp.company",
                    ),
                ),
                (
                    "skills",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="naukriapp.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=30)),
                ("project_description", models.TextField(max_length=100)),
                ("from_start", models.DateField()),
                ("to_end", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="naukriapp.company",
                    ),
                ),
            ],
        ),
    ]
