# Generated by Django 4.1.3 on 2022-11-26 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('availability', models.IntegerField(choices=[(1, 'Not Active'), (2, 'Active')])),
            ],
        ),
        migrations.CreateModel(
            name='Company1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('date_of_start', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=40)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('company', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='nestedserializer.company1')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('applicant', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='nestedserializer.applicant1')),
            ],
        ),
        migrations.CreateModel(
            name='Job1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('max_salary', models.FloatField()),
                ('min_salary', models.FloatField()),
                ('employment_type', models.IntegerField(choices=[(1, 'Fulltime'), (2, 'Parttime')])),
                ('max_experience', models.CharField(max_length=30)),
                ('min_experience', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('industry_type', models.IntegerField(choices=[(1, 'Computer and IT'), (2, 'Management')])),
                ('company', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nestedserializer.company1')),
                ('posted_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nestedserializer.skills1')),
            ],
        ),
        migrations.CreateModel(
            name='Experience1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('applicant', models.ManyToManyField(to='nestedserializer.applicant1')),
                ('company_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nestedserializer.company1')),
            ],
        ),
        migrations.AddField(
            model_name='applicant1',
            name='job',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='nestedserializer.job1'),
        ),
    ]
