# Generated by Django 4.1.3 on 2022-11-24 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Prefer not to same')])),
                ('availability', models.IntegerField(choices=[(1, 'Actively looking'), (2, 'Not actively looking'), (3, 'Offers')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('date_of_start', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Prefer not to same')])),
                ('company', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='N_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=20)),
                ('q_description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('applicant', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='N_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('max_salary', models.FloatField()),
                ('min_salary', models.FloatField()),
                ('employment_type', models.IntegerField(choices=[(1, 'Part time'), (2, 'Full time')])),
                ('max_experience', models.CharField(max_length=20)),
                ('min_experience', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('industry_type', models.IntegerField(choices=[(1, 'Computer and IT'), (2, 'Management'), (3, 'Education')])),
                ('company', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='N_app.company')),
                ('posted_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='N_app.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_description', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('applicant', models.ManyToManyField(to='N_app.applicant')),
                ('company_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='N_app.company')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='N_app.job'),
        ),
    ]
