# Generated by Django 4.1.3 on 2022-11-24 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=20)),
                (
                    "availability",
                    models.IntegerField(
                        choices=[(1, "Not active"), (2, "Active")], default=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Female"), (2, "Male"), (3, "prefer not to say")],
                        default=1,
                    ),
                ),
                ("contact_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=30)),
                ("location", models.TextField()),
                ("date_of_start", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("designation", models.CharField(max_length=30)),
                ("bate_of_birth", models.DateField()),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Female"), (2, "Male"), (3, "prefer not to say")],
                        default=1,
                    ),
                ),
                ("phone_number", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="naukri1.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=20)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "applicant",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="applicant_qualification",
                        to="naukri1.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("max_salary", models.FloatField(max_length=20)),
                ("min_salary", models.FloatField(max_length=20)),
                (
                    "employment_type",
                    models.IntegerField(choices=[(1, "Full time"), (2, "Part time")]),
                ),
                ("max_experience", models.IntegerField()),
                ("min_experience", models.IntegerField()),
                ("location", models.TextField()),
                (
                    "industry_type",
                    models.IntegerField(
                        choices=[(1, "computer and IT"), (2, "management")]
                    ),
                ),
                ("date_posted", models.DateField()),
                ("data_closed", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="job",
                        to="naukri1.company",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("skill", models.ManyToManyField(blank=True, to="naukri1.skill")),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=20)),
                ("project_description", models.TextField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "applicant",
                    models.ManyToManyField(blank=True, to="naukri1.applicant"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="naukri1.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicant",
            name="jobs",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="naukri1.job",
            ),
        ),
    ]
